### ISSUE TITLE
HQ Materials Don't Have Textures

### ISSUE THREAD

**Issue by echads** [danielbui78/udtu-unity-package#2]
After the .dtu detection the new materials fail to copy over textures from the .fbx HDRP/URP materials.
I have not tested Standard pipeline yet.
If the code is there and it is still failing for some reason, my guess is a default setting may be needed to import .fbx's with materials saved to a folder rather than built into the .fbx. The other reason could then be those materials or textures might need to be marked writable in order to access them. I haven't played with those API's in a while so these are just guesses.

![image](https://user-images.githubusercontent.com/37284476/148714670-95207d9b-f831-4781-b79b-ee12473086f3.png)

Checking "Replace FBX materials..." is what I'm discussing in case it isn't clear. Unchecked  the textures do copy using the NON high quality ones.

**Comment by danielbui78** [comment]
Sorry, it's unclear what you mean by "new materials fail to copy over textures from the .fbx HDRP/URP materials".  
- Do you mean it is failing to FILE COPY over the the actual texture files into the Unity project folder.
- Or do you mean the materials are failing to be ASSIGNED the correct textures for the corresponding texture slots in the material editor.
- Or do you mean that the Scene and/or Game window panes are not rendering the correct textures on the models imported from Daz Studio?

FYI, the uDTU Daz Studio plugin does NOT embed any texture files into the FBX.  Instead, it relies on the uDTU Unity plugin to parse the information stored in the DTU files and then copy the original texture files used by Daz Studio directly from the Daz Studio Asset Library folders into the Unity project folder.  So there are no low quality textures used or created -- just the original textures directly from Daz Studio.  Please clarify your exact situation by answering the above questions, then do the following steps to help us better understand exactly what is going on:

1. Make sure that you are using the latest uDTU plugin inside Daz Studio instead of the official Daz Studio plugin.  Use "File->Send To->Unofficial DTU" instead of "File->Send To->Daz To Unity".
2. Do not modify any of the FBX Export options, aka Uncheck the "Show FBX Dialog" checkbox in the uDTU Daz Studio plugin Send To dialog window.
3. Make sure you never have "Install Unity Files" checked.  If it says "Overwrite Unity Files" and you also have an "Assets/Daz3D/Scripts folder" and/or "Assets/Daz3D/Shaders" folder, then your project is already messed up and you need to delete the Assets/Daz3D folder from your Unity project and re-install the uDTU package with the package manager.
4. Make sure that after uDTU package installation, you do not have any Error message in the Unity Console pane when opening the Unity project.  If you do have Error messages when opening the Unity project, then please take screenshots with fully readable error messages and post them here.
5. After a figure is imported from Daz Studio into Unity do the following:
6. Verify that a prefab was generated in the Scene window pane.  If not present, then find the generated prefab in the Unity Project files and drag it into the Scene.  NEVER drag the FBX directly into the Scene or Heirarchy.
7. Please go to the uDTU dialog window's History pane and open up all the Import Events and take a screenshot and post it here.
8. Open the prefab file generated by uDTU import process and take a screenshot of what the figure looks like and post it here.
9. Go to the Unity Console pane and adjust the filter to show only Error messages.  Resize everything to be readable and take a screenshot and post it here.

**Comment by echads** [comment]
I apologize for being a little vague. I thought this was a known issue as it happens for me in the official repo as well.

I'll paste a few shots:
Step 1:
![image](https://user-images.githubusercontent.com/37284476/149237713-33acaa66-3bc9-4dc5-8f7b-d05a59279e2a.png)
Step 2: Check settings before export/import.
![image](https://user-images.githubusercontent.com/37284476/149239750-da46b365-6e20-4ba0-972d-b19828a0f2f9.png)
Step 3: Auto detect and import:
![image](https://user-images.githubusercontent.com/37284476/149240727-7fa10012-21d6-416f-aaf3-bfa38c993312.png)
Step 4: Add the profile (I have had the profile added before and the issue still happens)
![image](https://user-images.githubusercontent.com/37284476/149240852-c7ee377d-be12-463f-97c9-0a85a83f0116.png)
Step 5: Review what was created, here a "uDTU HDRP.Specular" shader was used however with the G3F I got a SSS shader, in either case these uDTU materials are added to the prefab but no textures assigned.
![image](https://user-images.githubusercontent.com/37284476/149241053-9054139a-3951-4080-960c-bdb92a570c0e.png)
![image](https://user-images.githubusercontent.com/37284476/149241170-a0123274-d16e-40e0-b316-1d57565fdb7d.png)
Now if I unchecked the [ ] Replace FBX materials with HQ ones...box the standard HDRP Lit shaders would have the correct textures assigned.

Like mentioned above this also happens with the official DazToUnity, am I the only one seeing this issue?

**Comment by danielbui78** [comment]
Thanks very much for taking the time to post your step-by-step screenshots.  However, you have not shown me a if you had any Error messages in the Unity Console pane.

Are you running Unity on Mac or Linux?  Are you running the Windows version of Daz Studio via WINE?  Are you running the official bridge for the Daz Studio plugin and mismatching it with the unofficial bridge for the Unity plugin?  While all these things are not necessarily deal-breakers, it would have been extremely helpful to know these things.  All of these things have different expected behaviors and implications when things go wrong.

As I mentioned in the previous reply, the uDTU Unity plugin copies the original texture files directly from the Daz Studio Asset Library.  It does this by reading the ABSOLUTE FILE PATH to the textures which is stored inside the DTU file.  Based on your screenshots, my suspicion is that the drive/folder/file mapping that is used for Daz Studio is not the same exact mapping that is being used or understood by Unity.  If you can please clarify exactly what platform you are running, what filesystem(s) you are using and what file/folder/drive mappings are being used, then it would help me understand what exactly is not working.  Also, please send me the Error messages in the Unity Console pane.

Thanks

**Comment by echads** [comment]
There were no errors but I did have warnings:
![image](https://user-images.githubusercontent.com/37284476/149290070-9d50013a-4f1c-4dbb-83a2-a85b290345ee.png)
Which now gives me the point of failure. Thanks!

Yeah I run a complex setup on linux running Daz on Wine / Steam Proton. And Unity natively on linux. I can also run Unity in Wine so it looks like I need to do that to at least grab the textures as linux doesn't have a concept of a C:/ drive so that is why it isn't finding the textues. It does find some textures though (which was why I thought some came through the .fbx) anyways I should be able to solve it from here. Thank you for helping me find the hiccup.

**Comment by danielbui78** [comment]
Sorry, you still seem to be confused on some very big points:
- There are TWO halves to the uDTU Bridge: an unofficial DAZ STUDIO PLUGIN and an unofficial UNITY PLUGIN.
- This github repository is ONLY for the second half: the unofficial UNITY PLUGIN.
- The first half, the unofficial DAZ STUDIO PLUGIN, must be downloaded and installed separately.
- To use the unofficial DAZ STUDIO PLUGIN, click "**File->Send To->Unofficial DTU**".
- Based on your posts and screenshots, you are _**mismatching**_ the _official_ DAZ STUDIO PLUGIN with the _unofficial_ UNITY PLUGIN.

The _official_ DAZ STUDIO PLUGIN has bugs and behaviors that are fixed and/or changed in the _unofficial_ DAZ STUDIO PLUGIN.  The official DAZ STUDIO PLUGIN will embed textures by default into the FBX.  The unofficial DAZ STUDIO PLUGIN will not embed textures by default.  This behavior can be toggled on/off in the "Show FBX Dialog" option of the unofficial DAZ STUDIO PLUGIN.

You are confused about whether or not textures are copied/not copied because you are _**mismatching**_ the official/unofficial parts of the bridge.  Consequently, you are creating very confusing and contradictory posts here because you are not clearly stating this situation.  This is wasting your time and my time and the time of everyone reading these posts.  Please try to understand this for future posts.  Thanks very much.

**Comment by echads** [comment]
I understand now. I admit I should of picked up on the UDTU repo earlier as you kept referring to it and I remained unclear what you fully meant.

So from all this to me the take away here is updating the README.md.

IMHO clearly mentioning that both projects need the other to be complete would be helpful. I scrolled through https://github.com/danielbui78/UDTU and found no link to this repo for instance. Just adding your bullet point:
```
There are TWO halves to the uDTU Bridge: an unofficial DAZ STUDIO PLUGIN and an unofficial UNITY PLUGIN.
```
And then linking to the tandem repo would do it.

However I could see the counter point, under https://github.com/danielbui78/UDTU#windows-installation-instructions where you mention:
```
The embedded Unity plugin can be installed with the "Install Unity Files" option, just like the official DazToUnity Bridge.
```

As being enough. Anyways, I will close this issue out.

**Comment by danielbui78** [comment]
No worries.  It is completely my fault for assuming that only people familiar with the original UDTU github project and follow my posts on the Daz Forums thread about the unofficial Bridges would even know about this repository.  This was obviously a silly assumption by me in the era of Google.
